"""Create tickets table

Revision ID: d122aa5172cd
Revises: 63b029192a7a
Create Date: 2025-12-12 18:14:16.729088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd122aa5172cd'
down_revision = '63b029192a7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
